### ISSUE TITLE
Questions about yzx->xyz coordinates conversion

### ISSUE THREAD

**Issue by zkf1997** [brown-ivl/ConDor#5]
Thanks for the great work!

I am trying the pytorch version code and find there is a [yzx->xyz coordinates conversion](https://github.com/brown-ivl/ConDor/blob/d9e03194134c46fc19935777360ad1259b7f4ab7/ConDor_pytorch/trainers/ConDor_trainer.py#L93C64-L93C64): 

It seems like the input points are in 'xyz' while the canonical points are in 'yzx'. I am wondering where this coordinates conversion comes from and may you kindly explain this?

**Comment by RahulSajnani** [comment]
Hi @zkf1997 
Sorry for the delayed response. Spherical harmonics are equivariant to yzx coordinates instead of xyz. This is why we always transform between xyz and yzx. If you look at the training loop of the network we do this conversion there too. We also transform from yzx to xyz for the canonical frame that is predicted by the network. I hope this helps you understand better.

**Comment by zkf1997** [comment]
Thanks for your kind response. It really helped me understand the reason behind the conversion.
